#include <iostream>
#include <unordered_set>
#include <string>

// Definir el tamaño de la lista de valores hash
const int HASH_SIZE = 260;

// Función para encontrar duplicados en la lista de valores hash
void findDuplicates(const std::string hashList[], int size) {
    std::unordered_set<std::string> hashSet;
    std::unordered_set<std::string> duplicates;

    for (int i = 0; i < size; ++i) {
        // Intenta insertar el valor hash en el conjunto
        // Si ya existe, se trata de un duplicado
        if (!hashSet.insert(hashList[i]).second) {
            duplicates.insert(hashList[i]);
        }
    }

    // Imprimir los duplicados encontrados
    if (!duplicates.empty()) {
        std::cout << "Duplicados encontrados:\n";
        for (const auto& duplicate : duplicates) {
            std::cout << duplicate << '\n';
        }
    } else {
        std::cout << "No se encontraron duplicados.\n";
    }
}

int main() {
    // Lista de valores hash
    std::string hashList[HASH_SIZE] = {
        "x{sowFDLHICFOHHEHH_@NFDLILHILDLU@C\\KOMLHH_KEMLOODC\\K_KDAG\\@CFDA",
"k~b||UDTEGC^GERAAALP^GC^RLPZUDC^RAX@HHD_JABXVH^GCZCOT[@FRAALPOE",
"jdeidflhgceonlc`edflh`gnlnlhgckkkkgnlnwmdfoflhk`gnamdflc`gnlnl",
"yfxx{UYK_PXX[KTYVRUR\\^PQXQXVRXMMM\\[VXPB_PURUYZUYVRMB_PMQXPXSU",
"pteno~xA@BQWHKH@BDHNU@BAI@T[GCQH@MAI@GCQWLFUOI@IKQH\\JH@BFU@BF",
"sgsrr[UIDENNNNC@ORIFRIDP@HBYIO@H@HEYIF[JBNW[JIDEFBHUIDJJM]NL^",
"akh|`sadkfoza}ahgjbq|oijkfckfc`slmfgck|aslmb|wfckf}wfcmfnj`y`n",
"bmvzvpquqyzrtubrv{hbvpmqjtubvpbkp|zrtuquququxwtuxsewtux~hb`spf",
"j}~{X^]ZRPXVEK\\KQOTKQO[YOP^TX@O[YOEKQOPX^R\\X^PXVRTX^EVGRFYZGRTV",
"ptduBEHKIBAVJB_HEH@XLQE^OFH@BESBKIBLUQAKESMOJB[K_SBEHKEHK[K[@BY",
"kxdfAIMDMOQL@BFFF_]KEHHKEHKEIXOQLHIDDAUMDXDWPUAUXOFTIDXWPUXL@BN",
"@VCFH@-<%('+9-:&:&1%--\"\"!.-*!!!&$ ,*!1%/-*!,+0 ,;*,&$((=.-:1%).",
"|zqq`YYYNNNNE_MYCBQTAORENENEKMNYNNYNYYYKBHJORV^Q@JQKMIFEE_MNEVD",
"v~oozKBSZBOEIKSBDYUYJQKXKSZBXAHJ\\C\\CQ@@KSZSZSZSZXKSZSBBSSSZX@L]",
"lq}OHE@@@@YZW@KDJ^TGFRCGQMLIIITRCX^TBQMPQML_E@CRCBQXHAJ^I_E@CRC",
"}szoo[]F^ONTJUZ[]FZ[RIM[RTU^DPG]FZVFVHFZKAIZVQNF@ONQNINI^^D[G]H",
"{q}xhxvo|CMEYJVVOWY@]@\\HS@RJV@]N]CXYP\\JZLPCI^^P^P_H^VBBXNRA\\UDN",
"dfz|jcxsn`zxsnvlekrrife`zmpqxgcb|jcanvankomp|jscliqbqxs{`zbj",
"f`na{spyqptvptv~v{s{rts|py||||qrtsqptv~|}tvwts|{~vsq~q~ryv{swt",
"apgijhxlr{hxvffamnvbiqavmdejhvfabpqaa`|hkvf|hxamc}z}ofaxlgmcj",
"dyQVQKX_KXTZV_YPS_V_NXQZNXQKXQV_ZYPSTYRPSTZVQZY]QZKX_KXTZY]QV\\",
"ctyrsYMLAG\\KEJFEJ\\KML]@GFMACKMLHI_C@C@C@GB^G\\@GFQ@LHJ\\@YXFPDJP^",
"HVWP 55*68?$-? *???)01\"#8)0#8 *?6862*?68 *)%#-$25*6868?$8)%1-)%",
"c|qtL_LTTE@Z^^HFYCAHF@OTT_OPTP_ZK\\GA^HFNX]YYNMBH\\AH\\A^^H\\A^K\\GG",
"qzyJEHBYA@KEDDHXLGIXLJEHIIBCGIMJEHIMCGIIMN@FXA@FXAKDDOFMNKEHBC",
"}zaGEIYDEIYDEICBALRC^ICBORYD[BAO@HFTRYZLRCSJYZAOKJCBZAD[BAD[XBL",
"u{uspspspspspwyfzyfzczrrxuwrxuwrczrxuwyfzrrxuwyfzr}usp",
"okhmp{|ced~wn}d~wcp{tufwcez{p{{{ppp{{lfwn}}}}svn}svn}svc{gbt|",
"vsgbQBYKCRAKKYK@BY@AKCXAEH@W\\DOHKCRAK@AKEHY@MZCXAE\\O\\DO\\DOHI]HI",
"qjjczkczmhfkypyikcplplh`b{q~jlplpyej}qlskgf`|xukuvywh`qlw",
"lbailofincmdr}mo`ml}maqkma|fzj`drnigamlrcjkdnin}mdchdcml{l`dc",
"hqvtb`~vsw{|sljtbgywphmq|~v~vt`~vtbkeljtkphmq|t`~`sw{fhbvtgyaz",
"hiihlihhhhhliafk{zzzobnmihaf`f`j{zzobccnbcnmihhhafk{zzomihhhhhh",
"fzsdv`JD\\NDQ\\CWPMH@II_YJCCW[DF[^@IGLJCLVAMHVI_]@TEMSM\\CCRFPMH@\\",
"fsu}dK[]R\\@@KP^RQ[QWPUZZSOZX\\YX\\YXWEUOZOZ^RARW[RTRQPU^[GQARW[QA",
"ujw}zhgq|uwp~vhkzh}|~vhgq|~}qq|j~}zhkolhvhrkow{{{yap~vhkow{p~kz",
"jxmu~vwXORJELPB@JZHJZSFCDBKKFCD[_LGLC_WIFJJJDAFY_LEGAFNHHHJBHBM",
"k}qamPZDQZZ^PU[U[UYQSLDQZ^EXQZZ^CYXQZUCK_VT[UCYFU[UYQZ^PZUPOHP^",
"yjjbtH@_EXXMH@_EM^@T[SMSDEXKHKHDEL]^D\\YUBP^ZNVTEMSDUMSDJN@IJYJ",
"zqXZVS[[[PXZRRVSPXXXZV^^S[PZRRV^^^SPXXXZRRRVS[[[PXXZV^SPXXZRRRR",
"qql~pIAU@WD@WOEIAU@LIW^BXKBBDKXCFD@LIWDW^BP_Q@AIW^BETH]UAHUAUAH",
"uxtswP\\VPQYSV^]YSQMU[TTTTT_\\VP\\VPQY^YPQXWWTTW_V^YPQMUPQYSVSQY^",
"c~~kxkpuyi`x{}t||zv|x{rr|p}|~{tg}t~zzntgr||{izvuzcu~~~zv{rgr}t",
"ive{ohlf`sry|jibskjpnpnlpnpcdryl{qrccn{{{ixbrnpcdsku~jedvdgcd",
"ckjxtrvhfaWZBKSSSS^_X^TUK^I_LXRAOXS^[ECRFK[__L[EVZBKHBQU_X^VRRR",
"zyqxcVP^]I@V_YBVTRSBV_YUTTIVPWPW_RQZ\\]TPS^YQZXBV_Y\\CVT]]RZ^RZQ^",
"fsobl}quxKUYQQF_IJRRZQK^XAZICHPNKJRDXL[FQQQ@FUQFXFYFV]MK^BNLPJ",
"fk~cq{vh~|}ntwzg`q{`|||}y`|||||ryv~|}yv~q{`||}y`|}cy`|uomb}cnt",
"fpkspfeisVIMDNJKBX[LRRGI[A@FX[WBBMDHH_V_V_@QCIBAPUQCVIDFBLHNX[L",
"eywfMJ_TNW]LLLLXJTNWGCNLW]MU]ADHMU@VNW]_BGNLW]ADHXU]W@VYADVCN_B",
"hkiswv{|}{|t}~sw}s|v{|}~swtvs|vp|tvswt}~xw}swt}{wtv{|ttzux",
"rcvgd`calmezpds`nif}ucawcli|||fkfkfkfgoedkqs`caliqs`hjucwhucwnb",
"rtnrRYXHWV_MTM_Y\\VE]_YXSRY\\V_QV[ERYM[TZUSSRDCS^][[[TYM[ERZURYX^",
"@BDL ,# !,#$\"+&%<01-:7.(*-+&;(*)*862*)*8+-$\"+-+8 (*8$)*-$)%<%)%",
"p}qlzCCYBKILDLINL_NQOHEXK^RLICNL^CQDCYBKSHRHRA_YXK^NFDCYQ^RL_K_",
"kbfcwcclh`hrsowwlh`th`hgd`hrszbm{nbm{ca{cwcccnbm{ccnbm{cwa{cwcl",
"pwzzdPSDNQW[\\NFDATINFDCFSSOPDW[FDYXF^]RLIA_NQLICFDWEH]]RWICKOP^",
"fv{LBA@HQI[XVO@HFUXKJNHULBWHI[BLX@HULX@HFFULBA@HFFFFFFUWHF_FQI[",
"~faicrpy`mcjzlkbzaqfykmyvyvcj|awfniaqfhj`jsujwfcj`mizvbzaq}~i",
"{`mlyC_P\\@FLK@AP^L@MG\\@L@M@\\@M@AFWYFM@MZZJG\\@WWAMGWYFLGAP^WNN^",
"fasdkfcalmez|ez|eoezfkfgd`huvzfkfkfkfgoedk|{ukfgo{ukfkfkqhucwnb",
"ti~BHCDHCED_NB_CDS_B_NB_BTDHNNCDHCEEZ@WWLUSTD_B_NBTDHCEDTDS_YBH",
"{azupA]NI@CJH_U^PAFNTRSXA\\KWAQ[GRI@MA@YHT]\\MWA\\R^PUTRZZ\\KARIZKA",
"{s~`s||RZVXY^FQ][RWSQUVSLH[OTRETU_FXNZ@T]R[O_F\\\\S\\QUTP^ZROTZVX[",
"yq`qo~huxq[Z[WOHCXWZJDRYS^QRXKU^XVKUSJOSSTWZ[LZUIKJDSSNCWD^XKUS",
"tr`bmtrp\\J_GUAK[DRFL]NA]CNNNNF[Z@Z@UAQMMKA]SBAGUHD]CYD]]NA]]GJC",
"|q|yAKPES^S^PP^S^^^TYCRBC]P_DDZKPHIMAKTC]ES^PS^^IBCRO\\BYU]_BCRX",
"pxjbMJEZYKES_Z@KP_DDHBC]SPE^SPP_DZYKPEDD^SP_DHIIIBYAKPPEDO\\OQBC",
"ekdlaswf{`gnjvmlpbjkw`}kyd~iml`}{`dhzlpnzlf{pcl`oyhf{`|aydsuj`",
"gbqtubwz|_NJEAO__JLH_IU^NAV@NXTHTHNU]]]GIEA^XNLNU^N^RRS^MZ\\FLCR",
"csz{~KCEAFLGHZTODDBFTDBKHHHON@BATDELCBLNFTOBLR@CBLNKHELNKHOCB@",
"yjeuoyi~irchbl``oj|||vqkdb}ch{xitxtenlvv|vkey}c~tpssdrssjqlec",
"hyrxssi]FWAPPPZN]]FWV[ZNG[ZIT^XQA[FVE^MTGZYGE^YGZ@ITPE^YHGP^QWN",
"gdgz|wwIPRUTFMMSCYE_VMBWXPXEDTFBYPGM^D_OVXWRYEOUJGXARYPQ]^ODICP",
"|qquTTPT_X]PPPP_XRX]PTPP\\]PPTTPTPTT_ZSU]Y\\]PP_X]TP\\]TPT_ZU]P\\RX",
"dsrLBJFKWHN[]CCNEEPERMKLXKLBHCN[]CNP[]CCCD_QIHCNEEEEEE[]CNPEPE[",
"nqpq~OGOAKPBOQQFHLBEXHLMHW[DHOLII_UIIEWELMFYU_RUJLBDFNDFNVANBF",
"azx`vzlx`hj}y`~ftwovzwzazg{x~|yv~ulxvsyo`~fuw~tw`~twkcmxh|ykyv",
"hyldzkzzdemqfid`d`f|lqf}g}l}l}lkfgn}auiuazoemn}}gcuebf{hjflgmcj",
"|{vcz^S]ZTMZURCV\\TYM^V\\WBYI[Z[^SRYMVQJTPZEQY[Z[ZIP]^^Z[ZURYMS]S",
"ibwDOYE^BEX^_E^^XTRCTYOCTC_DOCTRCX^IRRRRYE^^TYE^TRRRYEX_E^TYE^I",
"}tQPTQPT\\^^SXRP_^^^^^^^SXRXRXRXRXYRXRPXRXRPPPPXR_^^SXVUQPPP_Z",
"jdqfFQLSXYSQ_ZKY^^SQL^YSXCWTQPPPPUQ_RBPJRXCWJ]@BPUBPUXRB_]VUBW_",
"asiUPLR^]@^TRYJYJCX^GPUPL]@^R^RCX^_PAO@SJYJYO@^RCBAZAO@^IXHFIX^",
"}~cj}HCELAN^H@TCEN@T@GMJS]DGSQJELANMHNBQJ[D]@GOQJSQURNSF\\IRMIGS",
"fzdk``KTB[RLJN]VL@QII_NRA@QQQIEMS[RU_DI[O\\HJC]VAB[Y@IIGDHK_NNRJ",
"jns|zYBPHFDLUKBSKBEIBSSONFZXFEHGT_YBWIC@@@WIBPHQAHUKBDA_CKXQWP^",
"mg{kr}dghkighcxjhplshy`jh{b}gh{bgsz|nen`i}cb}rsdq{qwecmjzmt`j",
"lhcwdjxveid{mnqkbmnfeizkh}nihaakmfelinihukdcfez`mealrzfelbbojlr",
"~on}dyzh{ojstclfsj~oasojskxez~`xpjs}evx`bvxw}hzkxdocas}~pj",
"hf~vZ\\MFZAG^EKQOTK\\MMLIT@Z\\MAGGG^E@OTKFZQZQZQZA]IP^TKQOTKQZLITV",
"@@EQK_6333>*%*.6(!,$>%$).89)2;'<\"7;'+7%:1$3,*.6,/$3>5 94?&$&*.<",
"a|vwtxwdrkwzqcnfvomjwzxl{qyenqylpyjix{xjjprvob}fv~jixpnqcd",
"twq}CBCMDDXLKNDBEHNOQLKEIMOHCXL@BEHHIOHIXLK@MOHHIOCBNDDOHIDOCBN",
"detgckpzcvp{}gnlswswjx`gnlswslx`gckpduw~`gck{gnlmdul~vdjmdjq",
"|h~ryBBMY\\]TT[TWRM]_VPSV^WY^XBXXMY^UV_[T[TWYZS\\YQBUDUPSXMUWT_Q",
"ani{yGF@MHIZ@YXFFKAFNZNDJHI^GRWI^]@MWA]@N^RARAQ[]@]FF@]\\@MWIZKA",
"|ulu[Z^TTYUGVGVRZQDYQZ^P\\]P^[Z^TEGWI\\]Y\\]TTC^WV]P\\]Y\\GVBZU]TTTV",
"eusC[LOJM^HPTFH[WJBKRMH[WJC[ACP[LFHTF^H[LZKGOJXRMH[LFHPPAC_OJX",
"JEQHWY 0,?)=*0$)'<98-)9-8-<<.-1$>?)2>=.<<1 0:*;9-+?)'67$-1 98).",
"y~a~elzR_@REVA]_VQQE^VCJPWJP[RTI_@RMQVQPPOX]_V[UE^[JARES_OB^V\\",
"xq~rHBYAHBYAHMMJEK\\AKE@KEHXLIMBCYA@O\\AHJE@OE@OEK\\A@OE@DOE@OFCCG",
"ymjdgdj`ul{pvczapmwgm}kffq|ulyydiiulpvsjmgecsj~qiiap`jkqiap`ly",
"n}u|xDLLLLWQ]LCDIJM]LLCLUJEHM]AO]WFF_DA_OGBPCAAO]AWFQ]WQRVB[EP@",
"nptkw~lLLTLAULALT[YJNYJC@[\\FDPALLWZMPTPHITPAUP_\\]IG@FD^NMEWD[X]",
"kjbrmdqyidhgyicjljafhoihdhgwm`fniotuvfdombewvfnidom`fntjpgcihhd",
"um{cqj}pntnl~jw~jffgnlqambpypypnazjwsvzbejlhvd`~bpypnwsvzjabejw",
"`lfuV^MMGAXBZ_BUVHIX[_EGLKLKABUZIBOA^MXMXP^MXPH_FNESOLQJEGA^W",
"~|{}@XAIDOIBHHKUA@MDONXLEHH@MDOIDBCOF@XAK_AIDMOIBHQA@XA@BNBNMDD",
"mhjmeuiwztp~vxvrgwyuuztp}ut~{xp~v~vxp}rupsyx{~vxutpv|rrvsutp",
"uvlzCNWTLDNAIA_KZUVOHEXK^RLICCCYCQIL^RERLUHRA_CKDYNFOEXRPSHHEX",
"z}}|NBNBFK_LKULEN]ADDDBHIBHIDDKECDDXAON_AJF]AON]ADONEIOF]ADONBN",
"exxmgckpznwi{}gckpozyfjbgnwmznsla`gnl~ken~`gckenwbgnllsllswmdfq",
"hlmj`ogvmqplxsxsssssc}z~}wv~zpwlmjwqvwv{zv~y}aojw|p~t{zpluw|z{",
"r{cvb{syRPT]RVNEZRT]W\\TMPPT]VMPZ]]VYZ]]KPQEYZ\\OIIIMSD^UIXKWAG]W",
"{hubqy{ZZ^C_W^ITC_UZ^[QSOJRUP\\RZBWGHIC_WRXZ^PBWRZHTCPU]]XH_WRZ\\",
"qunq|vsruxOZIODIRCLGIG_BEINUJRZFMOIZ_M]F\\^IGSROO@J@BRC[BFL@[QNK",
"`bee`lpc`hiv|f}|qpuq~m{uerzrvo}ivva}|xa}tzufuf}usuorvzupw",
"`lxgpkjzldfjvydgmilhvnenendfj`jvcnhenecy~iiloaccccnheyvn`j`j",
"tpxhtarvcqeyv~uu|oz{i{iptavhiarvcqpiwr`n~fu|rv~f|rvcuuf|zpmieyk",
"oeo|prcczakvj|akj|w|`dbmajzwtum`y{zzw|`ijn~`d{pufnsxatuqnscka`",
"rrfp`pyfZXRQMI[OWT]CRFJE]YFJ_GOAOPZMTRF@V_R\\UFHF^AZ@KM^[ZVCRQMT",
"lwyayowXD^PYH^EBQTYH^PBMZEMALE\\AWGJNXZS][AALEBMWY@JDHH^HHSQJNQT",
"s{txuCDIJFEIICDLY@GPKMCDGMHALU@AAHJBDIJOBOBQKMGEHAINFFEHUKFDGP@",
"`u~dm~auLJVFWLLWW\\YNTW_^VHBOU^DYUTPPBDSB[VHB^]RTBQ^KOEFEQ^G^KF]",
"kegterFBJCBWEFAEEQHVQA]UHGSFBUSQLFBAGPBHVFBXUBSTHVQ[@QAFPXUB^",
"fgvxlphTV@Z]MWS_Q_BS_JJNIGWDN_BUZ]JZ]BMAK@US[_UHBJHZG@MAWSPWHQE",
"nehtbfgpmpbaokhjhlgcjdkhlhackhadqbjhjokekcjhfgc`hwmekckdk{miwbj",
"hjkmqixvofoupaimrsoqttim}kgszqtttuwszueaim}}}rszfzupaixrhvz|xr",
"L^AC,='\" ='- ,!>'$(.(.-+->'-.\"/!.$(.-$*%!>'*&%&%,,=' ='\".$\"#%)%",
"}hmpu\\RE@JD\\^QT\\D]CX[_B]CCCXU_VEVJOV[BQTLOVUBRRRR[_VSNEBRDR[XUX",
"iw~uMEG@FBHFXRMEYYNBOBHFMCL_DPPP_WWL_DNM_DP_DCOMENMENXRMENMNMCD",
"f~lhjxq~p~up~tv~iwzpsyx|xuvxqziwzz|xkwq~iw}x||mwrv}rrvmlwrv",
"uzmlaj~jroZA\\QVAHOYZIZF\\[\\[BPROUNNDEQV@ABPM\\FABE[\\\\\\\\Q_[\\RD[HJV",
"a{jte~|alhebhjq}zecykmv|p}ebfzlhjsj~zoaaw}ld}ecneyd}lkxiwb~~",
"uw}kwR@]@]VX_DAINFDWFFOCL@R@OXIBWQGBWFIQGIIQGING_DWFQ]LVBLKUJU@",
"x|`b|`fzaifzlyoyhqfzlju`luvnnnrvchgifonyongic~innnfocljkfics`ly",
"ov~klx|njgzmgzmnk}xvfemcl}xiqijclxvzxt}mcl}}}rgt}xiq`zxivzmca",
"hnnsovb^MUFVZ_@@LJF@VXTHGDLFZIQGE^O\\H]FAHGPEHG@KCDLJYGDHF@LJFAH",
"Q@QSH7%;/60-.#/6!8(-'*$7!\"-&;/0< <'?9(-*:$!-9>*:/670-'5)18>.=&0",
"}~ouqU_XRWIZ^QT]TPWTRQIZFNTPAKAV^PSXU_YYNT]TG]TR\\UN_XWIZVP^\\RSX",
"MOB@\"/\"%).&$\"/-.(.-*4'$\"/\".1'+\".&$(.-/\"%!>'*&%&%,*&/&/\"%&$\"#%)%",
"pxnrd[KH]QLF@@\\BJA_JL[FL[VHZYUDOIC_JL[FDDDLFWWLJW[FZNUKNUZYJWVH",
"sye`}ieY^S]EFT\\L^S]DUMWN^^H[WFJE]DBN^SB\\Z[LSQILDBN^^SQT\\D\\ZEGTR",
"feqao|cqwzqpcsr|t|p}aixge~|zztqaxhrxq{}wvzif`vkg{vzp{`vyr|nr",
"ejpvcftg_^_W]LHTZP@[BDK[BCK[XTDYBIEUCVUY_I^_TJ]LSJGF]WCCUNSUCJP",
"g{muv~`vq`^B@FY]ZU_BF@I_BVZHLPPPCXSHMTD^FJOSC]X^QFYE]XHZYL]O^XL",
"aq|yuZU@OAINFOBEFDLJINGIEHG_NFOBNRWIPDWIBATEFOCGINFOBEHRWIC@DP^",
"ncohckfeinuvaaineainqjzcinjfjobjfhu`elfhgaaiy`elrinfj|mbud",
"adcnmpkbhgacmnhggbeacmidganjq`jaiykmlgmmw`}`einfnjeilukbfenu`jd",
"pofUFFUQ]SUUUFFUUUFF\\[SF\\[SFUQNS\\[SUQNSUFQYWR@B]_LWNSUFUUFB]T@B",
"ndqkvkOJXFO\\EX_XF[BBEXFFALSYI@NCI@OU]HH[AJIFAURUHDIQOOOFYIFFQ",
"i}oro`bf|_XYXYUGPKL^BHNY_THMHYC^BHYUGMHEFTS@@VZTHXBR^XXBSSDWWWE",
"gmjhjmxurr{wzgqkzrrpxsxz}xirpz}sb|}b|auwo`wptpzxhd{q|yvlgfiulu}",
"``d{hbZFN[\\[QVVGJDTR^IBZWZLTS]FPZLTSYTSSN]\\LTS]\\WD@UN]L@U]UR^IS",
"lbhgbvrbf{lncwqeo`hovmtjjggynam`tjjn}xiksihdtjnlzploeo`jg}d`hm",
"sdqu|xepjrEAN_WUGNAUFDGJORHFOHTFJD@UMYRHSKEAOHFNWUBI@UFUFNWNWNB",
"sdcrx`UBEX_JRR]X_JRR]HVZRPVZP_JYJYJREBPIJRRREMHD[LCAJNZPK^ZP_JR",
"`qbirh`xttsVZXQSR@SS]C^@^UHUS]YSGO_]^UBRIPDGDHYB^KI[RMEEKCHY\\PD",
"izhaylgtiauqbbmu|`nff}dqxvrjdfbfyo`pjo`nf}df|k`nbmkalsfbfdfmwh",
"`b|mdZUW[UW^XCCYFUL^NW[QSPT_NWDVT_CVTPT[\\CCV_\\Y\\NLSEB]UWTEXQWP^",
"JCCCHOGK$' %5</\"*'':#,-&*.&*6)7-4#%-</-4#.?'$.%-%*$.1.</8;7-6)'",
"kq}}}fDDDVSVHDZ_BKSUJTDOG^BUUDVSJTDOB@NFCBZ_JIXEASJIAHDOLIBVHEL",
"~lgfri~lrvVLOKYVRTB^]]Z^YP]]]]^Y[WSYOKUW^Y]^YVWVWPE^KYPXQ_\\RWS^",
"j{{xuo][ALZZMU][\\\\QMV[F\\WAFWLO][FWVZ[\\U][U][F\\LO^Y^RRRH^][AU^RH",
"tabmp}wgdy}g{ljiajemy`~mcz~mnndcoj`ygajdfmndccc`hmdegajkmcisgeu",
"pi{nymNBCDLT[@Z]^SFNWEY^]JDPW_@DRI\\NA@GJWENLTXYHIM\\NBYHIFCZZD",
"ybjn~jccbfvbqellakak|zvjbfvjmpllwqbfklwfvjmplww|okfvjmmplfklgok",
"aranceadnhpfmdnhkgkod~g`dniom`dg`dg`d}kzjdbwj`~g`fomwjfmailom`c",
"jogekeohgflfl~mdonocgwmdj``k`gced~ml~mdno~beo~biitmfwmoncgcgnno",
"LHIB,&-,<'&-$/$$----$ %&,>'&7'>'&----//$$$-$ %&,&--,<'&-/$-+#)%",
"{hxv\\ZPSTVRT^\\Z\\^PIWYUZP^\\ZP^T^P^TS[]UZ]ZPV]Z\\XXVR[]IW\\S[]^T^QZ",
"rotvu{ecTKPWCJ]W^VX]KP\\HDUM]LEYL[JRMOLZZY^O^^KVM]VSI]^Z^^PAQBN",
"~i~qtGRDZKDNIAKLIZKAG\\RDZ\\@MAJRZV[XUIO[M[MBXV[X@MA@MMMW@MLFBX@E",
"klbhjwmvwq}wprz|{}qw{zk{}a|wp{}|xjw{z|rzzq}wq}fvz|g}p{r~zcu",
"m~stYBJIBJL[KBS@LEIMCGJJABC@ABJJ_C@^GYMDMYBABNGJF[@AHO_YBZJIP^",
"jqokncvycwu{yclwr|ca}gsmfzllwrizaruupzz}rpipipppzzvfzzr|xu{",
"jzn}`SZYMN\\XQET[]\\BPSHRTPDW_YJQPZU@WAH]QLUKBSOXFZYUOXFDAT[RIC@L",
"iccbfclz`z`dftfn|a~slbhhfcbsaslkj`oiozkfecahfpoclen|ltfopa",
"l{gxNNCFFFKJRXGEYYCDIHF@BPECL^^^HFQLPTLTWJRXGENNCDG_LPPEBHFFKCD",
"FVJOMO_LN]'' ,-,&'1+**(:&8%%+2' <.0 -(!>!\"0 3 <!*#)/$#,& ,=**!-",
"KAZJHR!1<;+69%*\"\"$&->%$*'\"8(!1%&#0*$&\"#;6.+ ')1&-'8(((0*\"4%!'-\"",
"vbfaygoypc~{hdd|q}pr}udiw{f|qaybccbbx|yemdbbxnoozqpecmccm`cyjv",
"puhcw|jXTGRN_QQVN_\\ZIM^^^POTRY\\MWJQJ\\TOT]_U\\TRRWK^A^^CZT]\\GGGR",
"`ey`veirin`wbxirgicqqqbmcircfmgtt}`wkjvp{xgtir}wvqqm}z||ep|kj",
"atlqpfDQI[YVANU_]RXGLVW_D_VW[NOFS[CW[RBPB[RA]U_YOQTBGANNC@_]]CA",
"aibnidi`mnekgni|akdekikplxwakdd`dddkijc}akg}lgcpakdjfgcekplgmcj",
"`vxtpwwMJPBDBDKCKCRIOED@NWRIC@HJMGFKCJBDENCIDMMBDKNNNWTCJBF@^IC",
"vud|tbEZBWXUOCPSYNTP^PXDA^CITCEOYEPXIITEDI_DIUJ]RULG^INIC_ZMBW",
"c~ij}fZTDV^BJ]_XPNZIXXPCWY[IBUUZ_XP^W]_BDFCJYLTDFYW]IMSOLIXXWYJ",
"ffboiokhaj`loidoggtynh|nhfemajgtchfebij`fembijg`femlo`ldog`ldok",
"g}jwHFL[WB^HP_ZOUTQFLTF@]RBHQ\\CZ@RU[WU_OJB^HFH[^^HQQQFHP_ANXRJX",
"ogcephjfknqkbud{}fhj|bdombhjquhjfhu`elfhgl}fvlfhjfvaaaalfkbd",
"sqhp~gzk@WRKYKNM@IRM@P@WCJUNXQHYSSHCURBPHTTUGMV[BNBY@_IGMVL@]L@",
"qynzqo|wBIEKYKNM@IRM@P@P@GBNXQHYSSHCURMKY^CUGMV[BNBYKCJJJYKCJL@",
"lcbfla||}~s}s}nv}x~wxuqwnv|ppqxs}zt~srs}s}z}wyp|rsr~~~sgvtxzt",
"edaq`khjgqbici`w}i`wyhyjgkxmujcwjndcl{j`asdjfmldnemjcwj`pfyhqm",
"xcoypq~iBDY^YBYNIHBYXI_STDNBDYY^XDCU_^CKQFRE^EUBO_DZQ\\RB^CVL[]W",
"ytx`p}YZ\\YZ\\YA_RZQXURQRZXK_[^A_]RZ\\[VQROCZZZBKXBIIURDLRZBTUAIU",
"ogqjsxbtqpszEAHEIUC[WUCQNGFUNIJ__LOVN@HFB_H\\X_^EIJNWUYORO@NHJ_E",
"qqp{iRSXW_YFSXAICVPOBPU[XXX\\]Y\\RFZUVPWTRQDLUVINFZOXXAT[UPWIVPAT",
"fk~eeaipg~lllwnh`ecv}ztfdfojtfodfofd}odfd}offdjielh`ec`pgn~wckg",
"cypxodo{|vzdqwnrqufwyrmkldfyguqldfibm~m}zd|v}zc~mkazau|ngu|ka",
"||yzZ^VGWV]_^[VRZ\\XYQZ^P\\]P^TPQZ^ZSU\\]Y\\RZSSBWV]TP\\RZ^Z^ZU]TTTV",
"yqrmteFJFLOKFLOKJFEF[KLZ@IWNGFUGWILZKAI\\WNDQFM@ND\\AD\\[Z@CSQFLO",
"cpofoe`a{f{}`wpl}q{f`gmndzcijml}}}`wpvwvlfvwkqpawvlnszm}kffpand",
"gzaov~e`opqgg}|mqm|qma~p~{qop~pqrpqr{|m||m||wg}qmq}xvop|",
"vstvKXAGDDXAJMF[A@CK[LKEIB@CKXL@GDDXAJIXLUAGOJIDDBFOFDOFDDXLKBN",
"frdyok~jroZA\\\\^N]]]]AB[XMY_EAF\\\\HOOY_PGPBTPMGAMYOGAMF^UN]]L]IKV",
"fws~hrE^FAQKZATHQK]F]\\B]FATSGESYLSCPRKA^\\M@KR@MKN[[ESYLIK]FLHTS",
"|ul|DMBOOCEIBLI@MKL^WNE_PHFDKA_EIBA^L\\JEFLSDU@XUKAIMM@XJEFDMK",
"H^TNCUU?&%,*-0.;%1$')&%! :)<%!\"<;-,)&-%#/?<06*87+*8,?<876$'=?&%",
"z`pj{pa}DYHTUSO^UTUSBDOE@R@RDDHXBDNTCU^UNBBCUYDIE@ROUCUN^U^E@RV",
"bd~chtx~h|z`npify}`ofyg`z`zygj|uqi{sa`uqm}`ufd}kmifcg`d}h{yra`",
"hfcwpelxv~qpr|rqp}p|xatammm}ppr|qukg~|}puwhvg~|xly`{o|}rq{z",
"amgqm}wlwq}xstz}m{wa}pnio~jlv}m{agkp|w|||||ww||wfmpzg`xtozgk`x",
"x|j`qdqxBOX@HBCKXKBDYRTBJL_CJWL\\HTXHXK[NB[CHMTBWQS[CSE@^OLE@TM@",
"yszxwscXIH^X_O^YE^VXUESYI^YTZPR_XTV\\\\]\\]Q\\A^Y_ZYYYVX__UXTO^YV[",
"btyn}noHFNGDWCSQTSB\\AZB@JZMW@TGPF@@AOXT]GZKB\\TS\\TP^QLGZYFKVZ@TE",
"a}~mtdioOXHE\\CNQ^ZSQSFK[VILFBJEDVTW_@T[@TXSEQ^GDKJCCRIITPM@IPBA",
"mszzoC@@NQW[\\NFDATINFOODWPH_NQWEH_YBPS^GFBPDWEU@NFSDATTTPOX\\KP^",
"bvg~aitqux|quxuvt~gsnumfzw}q~injxqzpzpsyuvicvtqsyzfztvpzt",
"tjzytHEBEICKBEBDFU@LOHRLDFEBOMCKIYBOHEHRWIYXFEICNFDLRA_CKBOBRAH",
"h`svG\\AKARZFX_ZV\\RZFYIZVEU_ZQ]AVM[MWMA\\KWQGQR^^Z@M@M@MKPA]AVPA",
"ebytgdwpznjxv{rwpswswjxvivivp{}}rw{njxuwsl}mnq`qz}rwf~``q",
"zxzmxm@TK_AC@TVCVROHKGB_AYJNJYJYJYJNUEJV]CA]]CALD\\IEZ^EOQHVRBEJ",
"s~rpmbYUFXGFMS[NS[NJYZSQINH@NHKKKKK@N\\S\\SJNSJI]NJYKK@Y@A[C_OMHJ",
"aots}pj@XZHPBY@\\HZHDNPXZSTNPXEIL^ZHDNETUIVXDCTYVXDYLSTY@QGGRC_W",
"BMOJUYA3'( <4'*19$:-=%):->1 )/#-+*16.->>$*\"!%166 =;4=>&.(6.%&#-",
"~|jxiguzh{zhuu{ynuuqhqswdpln|ibz`cxksjz`noksfrb~vnfycb~{ynz",
"ebca`onmnjieilixhqhdbafjgfed`kkeobbbedliedagd`anfblo|hijncccccq",
"hfzvz}|]QEZ]MWS_BQEDCMMGNC[NP_BUZ]JZ]BBMBML_JRWOJHDYC@BM]M[CMQE",
"`uslkw{}EGNIXDCVPWLLWWLLADNIMPLW\\]RTEU_JWL_HXVPPLEK\\HM\\HI_YDCK\\",
"U[RSXCOB-=/&\"2-80<$+=0-*!7\"0&75&\"21*7=$&$ !**,.'4&3)0.'49019$&/",
"q{ifwhEHFNHI]AGFZ_BNHIBZQZFRSS^FZFR^TRHTCUNHQZFJGUUN^FZTNSGFBCU",
"hjo}afjb`kshss{x{uzrzyr}`sastvzxnzcsctqx}vv|qijs`{iuqyra~x{|a",
"g{or{D_BEBIGMF\\[JAWGBIHNDHR@IHCJALXPN]WHCLKPYJC]AAL@P]A@GBPJOH",
"vdtgr{||UARFNFKIA@AFN\\ULFBXHOMV_GF@JMKILF[DKAC]NLZKIAF[ZHCC]CNC",
"w|dfsbpvvCUNCHBIUYD\\ELHSGITCBDMPFOYSTYDCIG_LKECURMDLON@K[OAUUUU",
"kx`|NBNBFK_LKULEN]SEHIOIBCDDBYKENXLKPIZNB\\ZY@AUWQXL@AUA@W\\DONBN",
"BOJTE7%0-*0-#*.= = ))'/+,\"\"*7%-\"*7%0\".$,\".'/ +,\"#<=6! ?**0--#*,",
"vurs^Z]^SW\\XV]YYZYYZWQ^PWQVY]^^SWZ]ZYYXV]Y]]YZYYTVY]YRPWZ]YTV",
"acpnpgwggg}fgg}|mqg}y{ottt{fga~vqgypnpnev|m|g}|w}fn{zmm|xjw",
"KNOV =;,7=0-$*'\".%#- *$->);!9'-:3* */7=%.$- ='*%9 =%9:>)0-$-))%",
"edwyaotuhehc`rnfurn|a`{ajfzbn{ajqvdrgk`ghfunil{jf}brrchpzbnehqu",
"jkaumdx[R_CNYDHZG]]GG]]R_YOXS_CHOTMPFAFIXUTENCS_DPQWLYCFIMWWWL",
"jwqy|xab_HOE\\NIA_KTLZZHZZZHBAFKFGS\\CHGSQ^DTBLZZHM@IKTBDTPM@IWEF",
"uwhykYKKKKVX_S@S@ON]WNRYVXDRN]WUQ]WYPY@UUQBQRNRNVBW\\[[[PNVBQ]SV",
"nbb|bmkohk`{j`p`j`{effmdcsc{fmdcinigk`{u}|mal{jfjkgfmaapkrhvkn",
"B\\HKHON&)&.(<$)-*><$'.!   -)&.,)&.%'9,%.%..,)<$7><$(&,...,%.,=>",
"g|tdjnfr~{qhs`bfbzlr`bflyafilyxahet~pyafliboxqnfjixfmziliw",
"`ipz|joP^Y@DI\\\\TGU^PSJU@]^YI^PSCLKYTDTGJA\\RNWU^BCUOJXD]^L]HTIQ",
"vopktqmn{`{p|lvcyoalvmyhj`lv}pfjbow}{wqq`{{a{lcsjbhv}pmrjkvc",
"|skIEIYDEICXBDPUXBRC^ICXBZWKFFFFFFUX^TRN^ICBRYOOODCBZLALLLAAKUB",
"`macvg~itvq~`ckq~tiitv}cvg~iititiiiiiip~iitiiiitp~vqza}cvq",
"aedjuf|gwl`zhhhekmnkfsj|ggd{wanggouangangzhuwlv|gdtebfte`glgmcj",
"d|dw|NANDJ[[PNEY@JD]ACM_VMHECXIHWQGM_OHPCMHPNECB\\HWFQ]LVB\\H[EY@",
"bwhH_[_LWN^I[IPFUFFUB]^IPUUBRCBRYZLWCB]H_P\\ZP\\DNHIPQRYOZPFFUX^T",
"ablfnbk~opjnsfaa`zirtgldmklzka|ldfgk|a|lngwiog{dsm`}ida|lnh`klc"
    };

    // Tamaño de la lista
    int size = 260;

    // Encontrar duplicados en la lista de valores hash
    findDuplicates(hashList, size);

    return 0;
}
